### ISSUE TITLE
 ELIFECYCLE  Command failed with exit code 1.

### ISSUE THREAD

**Issue by aweb-01** [rigwild/raspberry-instock-check#3]
Hey, really cool bot, thanks! 

Unfortunately I'm running into this error causing it to crash, at which point I have to restart it every time. Any ideas?

```
FetchError: request to https://rpilocator.com/ failed, reason: getaddrinfo ENOTFOUND rpilocator.com
    at ClientRequest.<anonymous> (file:///home/user/raspberry-instock-check/node_modules/.pnpm/node-fetch@3.2.0/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  erroredSysCall: 'getaddrinfo'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^


TelegramError: ETELEGRAM: 400 Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 696
    at /home/user/raspberry-instock-check/node_modules/.pnpm/node-telegram-bot-api@0.56.0/node_modules/node-telegram-bot-api/src/telegram.js:291:15
    at tryCatcher (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/user/raspberry-instock-check/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21) {
  code: 'ETELEGRAM',
```

After this it's a bunch of telegram info, then finally:

```
Node.js v18.0.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by rigwild** [comment]
Hey 👋 Is it an error on startup or after hours of running? Sometimes the rpilocator website shuts down temporarly.
The telegram error is because the error message sent to telegram is too big, I pushed a fix to limit its size.

I added a tutorial to auto-restart in the README.

**Comment by aweb-01** [comment]
It's usually after a few hours of running. Thanks for the auto-restart, that's helpful!

BTW - unrelated question, is there a way to configure it to only send a notification for certain regions? I tried editing the config to replace the URL with https://rpilocator.com/?country=US but that didn't seem to do the trick.

**Comment by rigwild** [comment]
> BTW - unrelated question, is there a way to configure it to only send a notification for certain regions? I tried editing the config to replace the URL with [rpilocator.com/?country=US](https://rpilocator.com/?country=US) but that didn't seem to do the trick.

Here:

https://github.com/rigwild/raspberry-instock-check/blob/81d6e57843ff1f42b78e680b359b11dc096e8d55/index.ts#L74-L77

Try:

```ts
    rawHTML = await fetch(`${STOCK_URI}?instock&country=US`, {
      headers: { 'User-Agent': 'raspberry_alert telegram bot' },
      agent: PROXY ? new HttpsProxyAgent(PROXY) : undefined
    }).then(res => res.text())
```

**Comment by aweb-01** [comment]
Thanks! 

Last thing... tried the auto-restart, probably an issue on my end but FYI here's what I got.

```
user@debian:~/raspberry-instock-check$ TELEGRAM_TOKEN=XXXXXXXXXX TELEGRAM_ADMIN_CHAT_ID=XXXXXXXXXXX TELEGRAM_CHAT_ID=XXXXXXXXXXX USE_DIRECT_PRODUCT_LINK=1 SEARCHED_RASPBERRY_MODELS=RPI4-MODBP-8GB pm2 start pnpm -- start
[PM2] Applying action restartProcessId on app [pnpm](ids: [ 0 ])
[PM2] [pnpm](0) ✓
[PM2] Process successfully started
┌─────┬─────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name    │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼─────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ pnpm    │ default     │ N/A     │ fork    │ 16604    │ 0s     │ 15   │ online    │ 0%       │ 18.8mb   │ user     │ disabled │
└─────┴─────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
user@debian:~/raspberry-instock-check$ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/user/.pm2/pm2.log last 15 lines:
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] online
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] starting in -fork mode-
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] online
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] starting in -fork mode-
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] online
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] starting in -fork mode-
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] online
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] starting in -fork mode-
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] online
PM2        | 2022-05-09T18:53:41: PM2 log: App [pnpm:0] exited with code [1] via signal [SIGINT]
PM2        | 2022-05-09T18:53:41: PM2 log: Script /home/user/.local/share/pnpm/pnpm had too many unstable restarts (16). Stopped. "errored"

```

**Comment by rigwild** [comment]
Oups my bad. Looks like PM2 does not support pnpm. Use `... pm2 start npm -- start` or `... pm2 start dist/index.js`

**Comment by aweb-01** [comment]
> Oups my bad. Looks like PM2 does not support pnpm. Use `... pm2 start npm -- start` or `... pm2 start dist/index.js`

Perfect. Thanks a ton!
